### ISSUE TITLE
Duffy client tracebacks when session_lifetime is float instead of integer

### ISSUE THREAD

**Issue by arrfab** [CentOS/duffy#510]
Just updated a duffy api server and client (different node) to 3.3.0 and I see the following behaviour : 

Extending (for testing purposes) the session_lifetime* : 

```
duffy admin show-tenant arrfab
OK: arrfab: id=2 node_quota=None effective_node_quota=10 session_lifetime=None effective_session_lifetime=6:00:00 session_lifetime_max=None effective_session_lifetime_max=12:00:00 active=True created_at=2022-05-24 13:36:43.931923+00:00 retired_at=None


duffy admin update-tenant --session-lifetime 365d --session-lifetime-max 365d arrfab
OK: arrfab: ssh_key=********** api_key=********** node_quota=None effective_node_quota=10 session_lifetime=365 days, 0:00:00 effective_session_lifetime=365 days, 0:00:00 session_lifetime_max=365 days, 0:00:00 effective_session_lifetime_max=365 days, 0:00:00
```

Now trying from client node to request machine : 

```
duffy client request-session pool=virt-ec2-t2-centos-8s-x86_64,quantity=1
Traceback (most recent call last):
  File "/home/arrfab/.local/bin/duffy", line 8, in <module>
    sys.exit(cli())
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/arrfab/.local/lib/python3.8/site-packages/duffy/cli.py", line 696, in client_request_session
    result = obj["client"].request_session(nodes_specs)
  File "/home/arrfab/.local/lib/python3.8/site-packages/duffy/client/main.py", line 123, in request_session
    return self._query_method(
  File "/home/arrfab/.local/lib/python3.8/site-packages/duffy/client/main.py", line 106, in _query_method
    return out_model(**response.json())
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for SessionResult
session -> tenant -> session_lifetime
  input value 31536000.0 must be a string or an integer (type=type_error)
session -> tenant -> session_lifetime_max
  input value 31536000.0 must be a string or an integer (type=type_error)

duffy client list-sessions
Traceback (most recent call last):
  File "/home/arrfab/.local/bin/duffy", line 8, in <module>
    sys.exit(cli())
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/arrfab/.local/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/arrfab/.local/lib/python3.8/site-packages/duffy/cli.py", line 670, in client_list_sessions
    result = obj["client"].list_sessions()
  File "/home/arrfab/.local/lib/python3.8/site-packages/duffy/client/main.py", line 109, in list_sessions
    return self._query_method(
  File "/home/arrfab/.local/lib/python3.8/site-packages/duffy/client/main.py", line 106, in _query_method
    return out_model(**response.json())
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for SessionResultCollection
sessions -> 0 -> tenant -> session_lifetime
  input value 31536000.0 must be a string or an integer (type=type_error)
sessions -> 0 -> tenant -> session_lifetime_max
  input value 31536000.0 must be a string or an integer (type=type_error)

```

Even list-sessions doesn't work .. but using curl to query API shows that node was correctly provisioned and I can still query for list-sessions : 

```
{
  "action": "get",
  "sessions": [
    {
      "retired_at": null,
      "active": true,
      "created_at": "2022-07-28T07:17:54.881381+00:00",
      "id": 40,
      "expires_at": "2023-07-28T07:17:55.174396+00:00",
      "tenant": {
        "retired_at": null,
        "active": true,
        "created_at": "2022-05-24T13:36:43.931923+00:00",
        "name": "arrfab",
        "is_admin": false,
        "ssh_key": "**********",
        "node_quota": null,
        "session_lifetime": 31536000.0,
        "session_lifetime_max": 31536000.0,
        "id": 2,
        "effective_node_quota": 10,
        "effective_session_lifetime": 31536000.0,
        "effective_session_lifetime_max": 31536000.0
      },
      "data": {
        "nodes_specs": [
          {
            "quantity": 1,
            "pool": "virt-ec2-t2-centos-8s-x86_64"
          }
        ]
      },
      "nodes": [
        {
          "hostname": "n27-38-42.pool.ci.centos.org",
          "ipaddr": "172.27.38.42",
          "comment": null,
          "pool": "virt-ec2-t2-centos-8s-x86_64",
          "reusable": false,
          "data": {
            "provision": {
              "ec2_instance_id": "i-0c65d44926ee4a79f",
              "ec2_instance_type": "t2.large",
              "hostname": "n27-38-42.pool.ci.centos.org",
              "ipaddr": "172.27.38.42",
              "public_hostname": "ec2-18-209-173-64.compute-1.amazonaws.com",
              "public_ipaddress": "18.209.173.64"
            },
            "nodes_spec": {
              "quantity": 1,
              "pool": "virt-ec2-t2-centos-8s-x86_64"
            }
          },
          "id": 40,
          "state": "deployed"
        }
      ]
    }
  ]
}


```

**Comment by nphilipp** [comment]
Hmm, timedelta objects (which ConfigTimeDelta, APITimeDelta are) are rendered as float seconds in when encoded as JSON. I'll change it so floats are accepted as well.
