### ISSUE TITLE
unable to interact with duffy since recent upgrade to 3.4.0rc1

### ISSUE THREAD

**Issue by arrfab** [CentOS/duffy#929]
Had a strange issue when trying to ask duffy for a node after the update was done for duffy code : 

```
duffy client request-session pool=virt-ec2-t2-centos-8s-x86_64,quantity=1
Traceback (most recent call last):
  File "/home/arrfab/.local/bin/duffy", line 8, in <module>
    sys.exit(cli())
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/arrfab/.local/lib/python3.9/site-packages/duffy/cli.py", line 696, in client_request_session
    result = obj["client"].request_session(nodes_specs)
  File "/home/arrfab/.local/lib/python3.9/site-packages/duffy/client/main.py", line 123, in request_session
    return self._query_method(
  File "/home/arrfab/.local/lib/python3.9/site-packages/duffy/client/main.py", line 106, in _query_method
    return out_model(**response.json())
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for SessionResult
session -> tenant -> effective_session_lifetime
  invalid duration format (type=value_error.duration)
session -> tenant -> effective_session_lifetime_max
  invalid duration format (type=value_error.duration)

```

I updated already to latest duffy client

```
pip install --user duffy[client] --upgrade
duffy --version
Duffy, version 3.3.9
```

As I still have access to server side, I had a look at my tenant, as yes, I had non default values for session_lifetime and session_lifetime_max : 

```
duffy admin show-tenant ci-infra-arrfab
OK: ci-infra-arrfab: id=3 node_quota=50 effective_node_quota=50 session_lifetime=3650 days, 0:00:00 effective_session_lifetime=3650 days, 0:00:00 session_lifetime_max=3650 days, 0:00:00 effective_session_lifetime_max=3650 days, 0:00:00 active=True created_at=2022-06-15 14:50:11.346268+00:00 retired_at=None

```

And it was working, so somethig in new code/db schema doesn't seem to parse that correctly.
I so tried to reset to default with `duffy admin update-tenant --session-lifetime NONE ci-infra-arrfab && duffy admin update-tenant --session-lifetime-max NONE ci-infra-arrfab`  and then was able to request again duffy nodes.

As soon as I tried to deviate from that, (and duffy should support that per tenant as it was working), it doesn't work anymore : 

```
duffy admin update-tenant --session-lifetime-max 3650d ci-infra-arrfab
duffy admin update-tenant --session-lifetime 3650d ci-infra-arrfab
```

each call with duffy client would return this again : 

```
duffy client list-sessions
Traceback (most recent call last):
  File "/home/arrfab/.local/bin/duffy", line 8, in <module>
    sys.exit(cli())
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/arrfab/.local/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/arrfab/.local/lib/python3.9/site-packages/duffy/cli.py", line 670, in client_list_sessions
    result = obj["client"].list_sessions()
  File "/home/arrfab/.local/lib/python3.9/site-packages/duffy/client/main.py", line 109, in list_sessions
    return self._query_method(
  File "/home/arrfab/.local/lib/python3.9/site-packages/duffy/client/main.py", line 106, in _query_method
    return out_model(**response.json())
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 12 validation errors for SessionResultCollection
sessions -> 0 -> tenant -> effective_session_lifetime
  invalid duration format (type=value_error.duration)
sessions -> 0 -> tenant -> effective_session_lifetime_max
  invalid duration format (type=value_error.duration)
sessions -> 1 -> tenant -> effective_session_lifetime
  invalid duration format (type=value_error.duration)
sessions -> 1 -> tenant -> effective_session_lifetime_max
  invalid duration format (type=value_error.duration)
sessions -> 2 -> tenant -> effective_session_lifetime
  invalid duration format (type=value_error.duration)
sessions -> 2 -> tenant -> effective_session_lifetime_max
  invalid duration format (type=value_error.duration)
sessions -> 3 -> tenant -> effective_session_lifetime
  invalid duration format (type=value_error.duration)
sessions -> 3 -> tenant -> effective_session_lifetime_max
  invalid duration format (type=value_error.duration)
sessions -> 4 -> tenant -> effective_session_lifetime
  invalid duration format (type=value_error.duration)
sessions -> 4 -> tenant -> effective_session_lifetime_max
  invalid duration format (type=value_error.duration)
sessions -> 5 -> tenant -> effective_session_lifetime
  invalid duration format (type=value_error.duration)
sessions -> 5 -> tenant -> effective_session_lifetime_max
  invalid duration format (type=value_error.duration)
```

**Comment by nphilipp** [comment]
Argh – With the session concurrency fixes  I did change these fields from returning integer seconds to a human-readable equivalent. I had an uneasy feeling about doing it but thought “which tenant (in their right mind) would even look at this field” and didn’t think of that the Duffy client verifies the returned structure (according to their – now outdated – specification).

**Comment by nphilipp** [comment]
> I updated already to latest duffy client

NB, server-side is a pre-release so the command to update would have to be:

```
pip install --user duffy[client] --upgrade --pre
```

**Comment by nphilipp** [comment]
Oh and it’s not a change on the Duffy end, but Pydantic V2 changed how plain `timedelta` fields are serialized, formerly as numbers (seconds) and now as a string 😢. These really are two issues: this change, plus the fragility of the client (which shouldn’t really verify the whole result, but rather only the pieces it is interested in).
